apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-operate-admin
  namespace: __PROD_NAMESPACE__
  annotations:
    ref: __CI_ENVIRONMENT_SLUG__    
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-__PROD_NAMESPACE__-static-operate-admin
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-__PROD_NAMESPACE__-static-operate-admin
    spec:
      imagePullSecrets:
      - name: aliyun-hk
      containers:
      - image: __IMAGE__:__TAG__
        name: operate-admin
        ports:
        - containerPort: 80
          name: operate-admin
          protocol: TCP
